name: pc_mart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_notch_bottom_bar: ^1.0.3
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  flutter_sslcommerz: ^2.3.6
  fluttertoast: ^8.2.8
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  image_path: "images/official logo.png"
  min_sdk_android: 21


  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
     - images/
